name: Deploy Payung Madinah Web App

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Deploy using SSH with username/password
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 145.79.13.14
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm --help
            cd /root/web/payungmadinah-web/
            ls -l
            git pull origin
            pm2 restart all